# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 7, 18, 27, 34, 927305, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
